name: CI
on: [push, pull_request]

permissions: read-all

jobs:
  linter-clomonitor:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
    container:
      image: public.ecr.aws/clomonitor/linter:latest
      options: --user root
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Run CloMonitor linter
        run: clomonitor-linter --path . --url https://github.com/artifacthub/hub
